08:26:27 [Skill] INFO  Skill:139 - Connecting to Furhat server on 192.168.1.250:1932
08:26:28 [Quiz] INFO  Quiz:173 - Starting skill
08:26:46 [Quiz] ERROR TriggerRunner: 33 - Error
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at Client.<init>(Client.kt:16)
	at furhatos.app.quiz.FlowKt$Start$1$2.invoke(flow.kt:90)
	at furhatos.app.quiz.FlowKt$Start$1$2.invoke(flow.kt)
	at furhatos.flow.kotlin.TriggerRunner.run(TriggerRunner.kt:31)
	at furhatos.flow.kotlin.Runner.runTrigger(Runner.kt:203)
	at furhatos.flow.kotlin.Runner.runTrigger$default(Runner.kt:175)
	at furhatos.flow.kotlin.StateRunner.run(StateRunner.kt:57)
	at furhatos.flow.kotlin.Flow.tailRecRun(Flow.kt:146)
	at furhatos.flow.kotlin.Flow.run(Flow.kt:110)
	at furhatos.app.quiz.Quiz.start(main.kt:9)
	at furhatos.skills.Skill.initializeSkill(Skill.java:176)
	at furhatos.skills.Skill.lambda$startSkill$2(Skill.java:234)
	at java.lang.Thread.run(Thread.java:748)
08:26:46 [Quiz] WARN  Flow: 93 - Flow unknown unresponsive, 12025 ms since last event poll
