15:39:06 [Skill] INFO  Skill:139 - Connecting to Furhat server on 192.168.0.24:1932
15:39:06 [Quiz] INFO  Quiz:173 - Starting skill
15:39:22 [ErrorLoggingThread] ERROR Quiz:466 - Exception in thread "Thread-5" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at Client.read(Client.kt:49)
	at Client.access$read(Client.kt:15)
	at Client$run$1.invoke(Client.kt:27)
	at Client$run$1.invoke(Client.kt:15)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

15:40:02 [Quiz] ERROR TriggerRunner: 33 - Error
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at Client.<init>(Client.kt:16)
	at furhatos.app.quiz.FlowKt$SendMessages$1$2.invoke(flow.kt:84)
	at furhatos.app.quiz.FlowKt$SendMessages$1$2.invoke(flow.kt)
	at furhatos.flow.kotlin.TriggerRunner.run(TriggerRunner.kt:31)
	at furhatos.flow.kotlin.Runner.runTrigger(Runner.kt:203)
	at furhatos.flow.kotlin.Runner.runTrigger$default(Runner.kt:175)
	at furhatos.flow.kotlin.StateRunner.run(StateRunner.kt:57)
	at furhatos.flow.kotlin.Flow.tailRecRun(Flow.kt:146)
	at furhatos.flow.kotlin.Flow.run(Flow.kt:110)
	at furhatos.app.quiz.Quiz.start(main.kt:8)
	at furhatos.skills.Skill.initializeSkill(Skill.java:176)
	at furhatos.skills.Skill.lambda$startSkill$2(Skill.java:234)
	at java.lang.Thread.run(Thread.java:748)
